name: install-ruby-windows
inputs:
  ruby_version:
    required: false
runs:
  using: composite
  steps:
  - name: remove pre-installed ruby
    run: Get-ChildItem -path 'C:\tools\' -filter Ruby* | Remove-Item -Force -Recurse
    shell: bash
  - name: download and install ruby devkit
    run: |-
      $ProgressPreference='SilentlyContinue'

      $uri = 'https://api.github.com/repos/oneclick/rubyinstaller2/tags?per_page=200'
      $releases = ((Invoke-WebRequest $uri) | ConvertFrom-Json).name | select-string (-join("RubyInstaller-" , "${{ inputs.ruby_version }}" ))
      $target_release = (($releases | Sort-Object -Descending)[0] | Out-String).Trim()
      $target_version = $target_release.Substring($target_release.Length - 7)
      $download_uri = "https://api.github.com/repos/oneclick/rubyinstaller2/releases/download/RubyInstaller-$target_version/rubyinstaller-devkit-$target_version-x64.exe"
      echo "Ruby Target Version Found: $target_version"

      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
      Invoke-WebRequest -UseBasicParsing -uri $download_uri -OutFile C:\ruby-setup.exe

      echo "Download finished, starting installation of $target_version"
      C:\ruby-setup.exe /VERYSILENT /NORESTART /ALLUSERS /DIR=C:/Ruby${{ inputs.ruby_version }}-x64
    shell: bash
  - name: ruby diagnostics
    run: |-
      $Env:PATH = "C:\\Ruby${{ inputs.ruby_version }}-x64\\bin;$Env:PATH"
      echo "Perl Version:"
      perl --version
      echo "Ruby Version:"
      ruby --version
      echo "Gem Version:"
      gem --version
    shell: bash
  - name: install bundler
    run: |-
      $Env:PATH = "C:\\Ruby${{ inputs.ruby_version }}-x64\\bin;$Env:PATH"
      gem install bundler -v 2.3.26
    shell: bash
